services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: problem5_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./src/database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d problem5_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: node:18
    working_dir: /app
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://admin:password123@postgres:5432/problem5_db
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
        npm install &&
        npm run dev
      "

volumes:
  postgres_data:
